version: '3'
services:
  # raw-data-mongodb:
  #   image: mongo:latest
  #   restart: always
  #   container_name: raw-data-mongodb
  #   ports:
  #     - "27018:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: # user
  #     MONGO_INITDB_ROOT_PASSWORD: # password
  #   networks:
  #     - raw-data
  #   volumes:
  #     - mongodb_data:/data/db


  backend-raw-data:
    container_name: backend-raw-data
    build:
      context: .
    restart: always
    ports:
      - 8779:8000
    env_file:
      - .env

# volumes:
#   mongodb_data: